[commands]
# A command maps voice input to a sequence of key combinations.
# A key combination is a set of keys to be pressed together, and is expressed as
# a string of key names separated by plus signs.
"Desktop" = ["LeftWin+D"]
# Although entering text is not the intended use of this app, some simple strings are doable.
"Commandline" = ["LeftWin+R", "c", "m", "d", "Enter"]

# Uses human-friendly duration descriptions from the `humantime` crate.
[timing]
# How long to wait between key combinations in a sequence.
sequence_delay = "25ms"
# How long to wait between sending a keydown and a keyup event.
hold_duration = "20ms"
