name: Build and release the binary
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build and release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          skip-version-file: "true"

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        if: ${{ steps.changelog.outputs.skipped == 'false' }}

      - name: Build windows binary
        run: cargo build -p voice2keys --release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          body: ${{ steps.changelog.outputs.clean_changelog }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          files: target/release/voice2keys.exe
