name: release

on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: windows-latest
    steps:
      - name: Run release-please
        id: release_please
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
      # The following steps only run if the release was created.
      # Since we use updateAll this should always include the cli release.
      - name: Checkout code
        uses: actions/checkout@v3
        if: ${{ steps.release_please.outputs.releases_created }}

      - name: Install the toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
        if: ${{ steps.release_please.outputs.releases_created }}

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --release
        if: ${{ steps.release_please.outputs.releases_created }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_please.outputs.upload_url }}
          asset_path: target/release/cli.exe
          asset_name: voice2keys.exe
          asset_content_type: application/octet-stream
        if: ${{ steps.release_please.outputs.releases_created }}
