name: Build binary
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os.name }}-${{ matrix.os.version }}
    strategy:
      matrix:
        include:
          - os:
              name: windows
              version: latest
            binary: cli.exe
    steps:
      - uses: actions/checkout@v3

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          skip-version-file: "true"

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        if: ${{ steps.changelog.outputs.skipped == 'false' }}

      - name: Build ${{ matrix.os.name }} binary
        run: cargo build -p cli --release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          body: ${{ steps.changelog.outputs.clean_changelog }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          files: target/release/${{ matrix.binary }}
